# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getSubscriptNum <- function(str) {
    .Call(`_ms2Spectrum_getSubscriptNum`, str)
}

makeIonLabels <- function(letter, count, dir) {
    .Call(`_ms2Spectrum_makeIonLabels`, letter, count, dir)
}

makeIonLabelsExp <- function(letter, count, dir) {
    .Call(`_ms2Spectrum_makeIonLabelsExp`, letter, count, dir)
}

makeSeqVec <- function(seq, fixDiffMods = TRUE) {
    .Call(`_ms2Spectrum_makeSeqVec`, seq, fixDiffMods)
}

isArg <- function(arg) {
    .Call(`_ms2Spectrum_isArg`, arg)
}

fixOD <- function(str) {
    .Call(`_ms2Spectrum_fixOD`, str)
}

getFoundIons <- function(ionTypes, ionNums) {
    .Call(`_ms2Spectrum_getFoundIons`, ionTypes, ionNums)
}

getSpectrum <- function(fname) {
    .Call(`_ms2Spectrum_getSpectrum`, fname)
}

