.ds HOME \V[HOME]
.ds PROG_WD_HOME \*[HOME]/scripts/ms2_annotator\fR
.ds PROG_WD_DB \fI\*[PROG_WD_HOME]\fI/db\fR
.ds SMOD_FNAME \fIstaticModifications.txt\fR
.TH "annotate_ms2 v1.0" 1 "28 November 2017" "annotate_ms2"
.SH NAME
annotate_ms2 - annotate fragment ions in ms2 spectra
.SH SYNOPSIS
.B annotate_ms2
[options]
\fB-p\fR \fI<sequence>\fR
\fB-s\fR \fI<scan>\fR
\fB-f\fR \fI<ms2_file>\fR

.B annotate_ms2
[options]
\fB-p\fR \fI<sequence>\fR
\fB-dta\fR \fI<dta_filter_file>\fR

.SH DESCRIPTION
\fBms2-annotator\fR Reads in a scan in a .ms2 file and attempts to annotate B and Y ions from a user specified peptide sequence. 
.SH OPTIONS
.TP
Command line options are processed from left to right. Options can be specified more than once. If conflicting options are specified, later specifications override earlier ones.

.SS MS2 FILTERING OPTIONS
.TP
\fB-mt, --matchTolerance \fI<tolerance>\fR
Tolerance in Thomsons (m/z units) for predicted fragment ions in .ms2 files. 0.5 Th is the default.
.TP
\fB-minC \fI<charge>\fR
Minimum charge state to be considered. 1 is the default.
.TP
\fB-maxC \fI<charge>\fR
Maximum charge state to be considered. 1 is the default.
.TP
\fB-minMZ \fI<mz>\fR
Minimum ion MZ to be considered from \fI.ms2\fR files. By default all identified ions are considered.
.TP
\fB-minMZ \fI<mz>\fR
Maximum ion MZ to be considered from \fI.ms2\fR files. By default all identified ions are considered.
.TP
\fB-minInt \fI<relative_intensity>\fR
Minimum relative intensity to be considered from \fI.ms2\fR files.  Ion intensities are normalized to 100 before labeling, so \fB-minInt\fR should be supplied as a relative intensity.  By default, all ion intensities are considered.
.TP
\fB-incAllIons \fI<0/1>\fR
Specify whether to include unlabeled ions in spectrum output file. \fB1\fR is the default.
.TP
.in +0.75i
\fB0\fR
.in +0.75i
Only include labeled fragment ions in spectrum output file.
.in
.TP
.in +0.75i
\fB1\fR
.in +0.75i
Include all ions in spectrum output file.
.in

.SS RUN SPECIFIC SUPPLEMENTARY INFORMATION
.TP
\fB-u, --unique\fP
Include spectral counts for unique peptides in output file.
.TP
\fB-c, --coverage\fR
Include percent sequence coverage for proteins in output file.
.TP
\fB-seqC\fR
Include sequence count for proteins in output file.
.TP
\fB-s\fR
Specify how to group sup info columns in output file. \fB0\fR is the default. One or more run specific sup info options must be specified to use this option.
.TP
.in +0.75i
\fB0\fR
.in +0.75i
Group columns by sample.
.in
.TP
.in +0.75i
\fB1\fR
.in +0.75i
Group columns by observation.
.in

.SS PROTEIN SPECIFIC SUPPLEMENTARY INFORMATION
.TP
\fB-loc\fP
Use \*[LOC_DB_FNAME] to lookup subcelluar localization information for proteins in output file. humanLoc.tsv contains Uniprot annotations for subcelluar localization by Uniprot ID, updated as of Jan 18 2017. Currently, sub cell location information is available for human proteins only.
.TP
\fB-fxn\fP
Use \*[FXN_DB_FNAME] to include panther category for proteins in output file.
.TP
\fB-seq\fR
Use sequence information in \*[SEQ_DB_FNAME], to include protein sequences in output file.
.TP
.in +0.75i
\fI<fafsa_file>
.in +0.75i
The user can optionally specify a fafsa formatted file to lookup protein sequences. The \fI<fasfa_file>\fR used to calculate protein molecular weights does not have to be the same as the \fI<fasfa_file>\fR used to search for protein sequences.
.in

.SS PEPTIDE FILE OPTIONS
\fB-g, --group\fP
Specify how peptides are grouped in peptide output files. \fB1\fR is the default.
.TP
.in +0.75i
\fB0\fR
.in +0.75i
Do not group peptides. In this format, each peptide will be output on a separate line in a long formatted peptide output file. Columns with information specific to each scan, i.e. obsMH, parent file, and scan, are included in output file. Only long output format is supported for this group method. 
.in
.TP
.in +0.75i
\fB1\fR
.in +0.75i
Group peptides by parent protein. A separate entry for each charge state of a given peptide will be included in peptide output files.
.in
\fB2\fR
.in +0.75i
Group peptides by parent protein and charge. Peptides found in multiple charge states will be grouped in output files. 
.in
.TP
\fB-modG\fR
Specify how to group modified peptides in peptide output files. \fB0\fR is the default.
.TP
.in +0.75i
\fB0\fR
.in +0.75i
Peptides with the same sequence, but different modification status will not be grouped. A separate entry will be included for each modification status found for a peptide.
.in
.TP
.in +0.75i
\fB1\fR
.in +0.75i
Ignore modification status when grouping peptides.
.in
.TP
\fB-n, --nullp\fR
Specify whether to include peptides with 0 spectral counts in long peptide output file. \fB0\fR is the default.
.TP
.in +0.75i
\fB0\fR
.in +0.75i
Do not include peptides with 0 spectral counts in output file.
.in
.TP
.in +0.75i
\fB1\fR 
.in +0.75i
Include peptides with 0 spectral counts in output file.
.in

.SS PROTEIN AND PEPTIDE COMPATIBLE OPTIONS
.TP
\fB-modS\fR
Include information about number of modified peptides. Columns for number and spectral counts for modified peptides will be included in protein and peptide output files.
.TP
\fB-mw
Calculate protein/peptide molecular weights taking into account static modifications. Static modification information is specified in \*[SMOD_FNAME] file in working directory. A blank \*[SMOD_FNAME] file will be generated at runtime and can then be edited by the user. Protein sequence information is stored in a fasfa formatted file. The default sequence file is \*[SEQ_DB_FNAME].
.TP
.in +0.75i
\fI<fafsa_file>
.in +0.75i
The user can optionally specify a fafsa formatted file to lookup protein sequences.
.in
.TP
\fB-smod\fR
Copy default smod file to working directory and exit program.
.TP
\fB-f\fR
Include columns for sample name and replicate number in long protein and peptide output files. The value for replicate number is taken as: <number> where the sample name is in the format <sample name>_<number>.
.TP
.in +0.75i
\fI<prefix>\fP
.in +0.75i
Remove \fI<prefix>\fR from all sample names. If \fI<prefix>\fR is not found in sample name, name is unchanged. In long output format, columns will be included for long sample name, short sample name and replicate number. 
.in
.TP
\fB-rev\fR
Choose whether to include reverse matches in protein and peptide output files. \fB1\fR is the default.
.TP
.in +0.75i
\fB0\fR
.in +0.75i
Do not include reverse matches.
.in
.TP
.in +0.75i
\fB1\fR
.in +0.75i
Include reverse matches.
.in

.SS OTHER
.TP
\fB-rw \fI<arg>\fP
Rewrite existing param files in working directory.
.TP
.in +0.75i
\fBflist\fR
.in +0.75i
Rewrite input file list.
.in
.TP
.in +0.75i
\fBsmod\fR
.in +0.75i
Rewrite static modifications file. See \fB-mw\fR for details on smod file.
.in
.TP
\fB--purge\fP
Remove file list, static modifications file, and all DTarray output files from current working directory and exit program. Only files with default names will be removed.
.TP
\fB-v, --version\fR
Print binary version number and exit program.
.TP
\fB-h, --help\fR
Display this help file.

.SH EXAMPLES
.TP
\fBDTarray\fR
Run \fRDTarray\fR using default parameters.
.TP
\fBDTarray -p 2\fR
Run \fBDTarray\fR, generating wide formatted protein and peptide output files.  
.TP
\fBDTarray -u -s 1\fR
Run \fBDTarray\fR and include spectral counts for unique peptides in output file (\fB-u\fR), grouping columns by spectral counts then unique peptide spectral counts (\fB-s 1\fR).
.SH AUTHOR
annotate_ms2 was written by Aaron Maurais. Email questions or bugs to: aaron.maurais@.bc.edu